---
- name: Add tunnel env
  ansible.builtin.template:
    src: etc/default/secure-tunnel.env.j2
    dest: /etc/default/secure-tunnel@{{ item.tunnel_service_name }}
    mode: "0755"
  become: true
  vars:
    tunnel_remote_user: '{{ item.remote_user }}'
    tunnel_remote_host: '{{ item.remote_host }}'
    tunnel_remote_port: '{{ item.remote_port }}'
    tunnel_local_port: '{{ item.local_port }}'
    tunnel_service_name: '{{ item.service_name }}'

- name: Enable secure-tunnel service
  ansible.builtin.service:
    name: "secure-tunnel@{{- item.service_name -}}"
    daemon_reload: true
    state: restarted
    enabled: true
