---
- name: Install required software
  when: vega_zfs_device != ""
  ansible.builtin.apt:
    pkg:
      - zfsutils-linux
  retries: 3
  delay: 3
  register: vega_zfs_install
  until: vega_zfs_install is succeeded

- name: Ensure mountpoint exists
  when: vega_zfs_device != ""
  ansible.builtin.file:
    path: "{{- vega_zfs_mount_point }}"
    state: "directory"
    mode: '0755'

- name: Validate data
  ansible.builtin.fail:
    msg: Missing parameters for ZFS module
  when: vega_zfs_device != "" and (vega_zfs_pool_name == "" or vega_zfs_mount_point == "")

- name: Create pool
  when: vega_zfs_device != ""
  ansible.builtin.shell: |
    set -o pipefail

    zpool create -f -o ashift=12 "{{- vega_zfs_pool_name -}}" "{{- vega_zfs_device -}}";
    zfs set atime=off "{{- vega_zfs_pool_name -}}";
    zfs set compression=zstd "{{- vega_zfs_pool_name -}}";
    # enable improved extended attributes - keep in inode instead of dir;
    zfs set xattr=sa "{{- vega_zfs_pool_name -}}";
    # reduce amount of metadata (may improve random writes);
    zfs set redundant_metadata=most "{{- vega_zfs_pool_name -}}";
    touch "/.zfs_created_{{- vega_zfs_pool_name -}}"
  args:
    executable: /bin/bash
    creates: "/.zfs_created_{{- vega_zfs_pool_name -}}"

- name: Create dataset
  when: vega_zfs_device != ""
  ansible.builtin.shell: |
    set -o pipefail

    mkdir -p "{{- item.mount_point -}}";
    zfs create "{{- item.dataset_name -}}";
    zfs set atime=off "{{- item.dataset_name -}}";
    zfs set compression=zstd "{{- item.dataset_name -}}";
    # enable improved extended attributes - keep in inode instead of dir;
    zfs set xattr=sa "{{- item.dataset_name -}}";
    # reduce amount of metadata (may improve random writes);
    zfs set redundant_metadata=most "{{- item.dataset_name -}}";
    zfs set mountpoint="{{- item.mount_point -}}" "{{- item.dataset_name -}}";

    touch "{{- item.mount_point -}}/.zfs_pool"
  args:
    executable: /bin/bash
    creates: "{{- item.mount_point -}}/.zfs_pool"
  with_items:
    - dataset_name: "{{- vega_zfs_pool_name -}}/home"
      mount_point: "{{- vega_zfs_mount_point -}}"
    - dataset_name: "{{- vega_zfs_pool_name -}}/home/vega"
      mount_point: "{{- vega_zfs_mount_point -}}/vega_home"
    - dataset_name: "{{- vega_zfs_pool_name -}}/home/tendermint"
      mount_point: "{{- vega_zfs_mount_point -}}/tendermint_home"
    - dataset_name: "{{- vega_zfs_pool_name -}}/home/network_history"
      mount_point: "{{- vega_zfs_mount_point -}}/network_history"
    - dataset_name: "{{- vega_zfs_pool_name -}}/home/postgresql"
      mount_point: "{{- vega_zfs_mount_point -}}/postgresql"
