---
- name: Install required software
  ansible.builtin.apt:
    pkg:
      - zfsutils-linux
  retries: 3
  delay: 3
  register: zfs_generic_install
  until: zfs_generic_install is succeeded

- name: Create pool
  ansible.builtin.shell: |
    set -o pipefail

    zpool create -f -o ashift=12 "{{- zfs_generic_pool_name -}}" "{{- zfs_generic_device -}}";
    zfs set atime=off "{{- zfs_generic_pool_name -}}";
    zfs set compression=zstd "{{- zfs_generic_pool_name -}}";
    # enable improved extended attributes - keep in inode instead of dir;
    zfs set xattr=sa "{{- zfs_generic_pool_name -}}";
    # reduce amount of metadata (may improve random writes);
    zfs set redundant_metadata=most "{{- zfs_generic_pool_name -}}";

    touch "/.zfs_pool"
  args:
    executable: /bin/bash
    creates: "/.zfs_pool"

- name: Create dataset
  ansible.builtin.shell: |
    set -o pipefail

    mkdir -p "{{- item.mount_point -}}";
    zfs create "{{- item.dataset_name -}}";
    zfs set atime=off "{{- item.dataset_name -}}";
    zfs set compression=zstd "{{- item.dataset_name -}}";
    # enable improved extended attributes - keep in inode instead of dir;
    zfs set xattr=sa "{{- item.dataset_name -}}";
    # reduce amount of metadata (may improve random writes);
    zfs set redundant_metadata=most "{{- item.dataset_name -}}";
    zfs set mountpoint="{{- item.mount_point -}}" "{{- item.dataset_name -}}";

    touch "{{- item.mount_point -}}/.zfs_pool"
  args:
    executable: /bin/bash
    creates: "{{- item.mount_point -}}/.zfs_pool"
  with_items: "{{ zfs_generic_datasets }}"
