- name: Install dasel
  ansible.builtin.get_url:
    url: "https://github.com/TomWright/dasel/releases/download/v{{- vega_common_dasel_version -}}/dasel_linux_amd64"
    dest: /usr/local/bin/dasel
    mode: '0755'
