---
- name: Ensure group "jenkins-agent" exists
  ansible.builtin.group:
    name: jenkins-agent
    state: present

- name: Append jenkins-agent user to the sudo group
  ansible.builtin.user:
    name: jenkins-agent
    shell: /bin/bash
    groups: sudo,docker,jenkins-agent
    append: true
    home: /home/jenkins-agent
