---
# How it works?
# OUTPUT: allowed everywhere
# INPUT: blocked all except 22 and specific ports

- name: Uninstall unsupported firewalls
  ansible.builtin.apt:
    pkg:
      - ufw
      - firewalld
    state: absent
  retries: 3
  delay: 3
  register: firewall_remove_apt_result
  until: firewall_remove_apt_result is succeeded

- name: Install iptables
  ansible.builtin.apt:
    pkg:
      - iptables
      - iptables-persistent
    state: present
  retries: 3
  delay: 3
  register: firewall_apt_result
  until: firewall_apt_result is succeeded

- name: Template restore file
  ansible.builtin.template:
    src: "etc/iptables/rules.v4"
    # https://www.thomas-krenn.com/en/wiki/Saving_Iptables_Firewall_Rules_Permanently
    dest: "/etc/iptables/rules.v4"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Restore firewall state from a file
  community.general.iptables_state:
    state: restored
    path: /etc/iptables/rules.v4
    noflush: false
  async: "{{ ansible_timeout }}"
  poll: 0
