---
- name: Config PostgreSQL | Create a new database
  become: true
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ item.database }}"
    port: "5432"
  register: create_db
  with_items: "{{ vega_postgresql_db_users }}"

- name: Config PostgreSQL | Ensure user has access to the new database
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    port: "5432"
    db: "{{ item.database }}"
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    priv: ALL
    state: present
  with_items: "{{ vega_postgresql_db_users }}"

- name: Config PostgreSQL | Change database ownership
  become: true
  become_user: postgres
  community.postgresql.postgresql_owner:
    port: "5432"
    db: "{{ item.database }}"
    new_owner: "{{ item.username }}"
    obj_name: "{{ item.database }}"
    obj_type: database
  with_items: "{{ vega_postgresql_db_users }}"

- name: Config PostgreSQL | Grant SUPERUSER role to Data-Node db user
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    port: "5432"
    name: "{{ item.username }}"
    role_attr_flags: SUPERUSER
    state: present
  with_items: "{{ vega_postgresql_db_users }}"
