---
- name: Restart vegavisor
  ansible.builtin.service:
    state: stopped
    daemon_reload: true
    name: vegavisor
  ignore_errors: true

- name: Get all files in vega_home
  ansible.builtin.find:
    path: "{{ vega_cleanup_network_home }}/vega_home" 
    file_type: any
    hidden: yes
  register: directory_content_result

- name: Remove the vega_home directory content
  ansible.builtin.file:
    path: "{{ item.path }}" 
    state: absent
  with_items: "{{ directory_content_result.files }}" 
  loop_control:
    label: "{{ item.path }}" 

- name: Get all files in tendermint_home
  ansible.builtin.find:
    path: "{{ vega_cleanup_network_home }}/tendermint_home" 
    file_type: any
    hidden: yes
  register: directory_content_result

- name: Remove the tendermint_home directory content
  ansible.builtin.file:
    path: "{{ item.path }}" 
    state: absent
  with_items: "{{ directory_content_result.files }}" 
  loop_control:
    label: "{{ item.path }}" 

- name: Remove the vegavisor_home directory
  ansible.builtin.file:
    path: "{{ vega_cleanup_network_home }}/vegavisor_home" 
    state: absent

- name: Remove vega-related databases
  become: true
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ item }}"
    port: "5432"
    state: absent
  ignore_errors: true
  with_items:
    - vega
    - tendermint
