---
- name: Stop services
  ansible.builtin.import_tasks: stop-services.yaml
  when: vega_core_with_unsafe_reset_all

- name: Prepare system
  ansible.builtin.import_tasks: prepare-system.yaml

- name: Get binaries
  ansible.builtin.import_tasks: get-binaries.yaml
  when: vega_core_download_binaries

- name: Build binaries
  ansible.builtin.import_tasks: build-binaries.yaml
  when: vega_core_build_binaries

- name: Get initialize
  ansible.builtin.import_tasks: initialize-node.yaml
  when: vega_core_with_node_init

- name: Prepare node configuration
  ansible.builtin.import_tasks: configuration.yaml

- name: Unsafe reset all
  ansible.builtin.import_tasks: unsafe-reset-all.yaml
  when: vega_core_with_unsafe_reset_all

- name: Start network
  ansible.builtin.import_tasks: start_network.yaml
