---
- name: Check local services
  ansible.builtin.service_facts:

- name: Unsafe reset all for the vega-core & tendermint
  changed_when: true # always impact the node
  become: true
  become_user: vega
  ansible.builtin.shell: |
    set -o pipefail
    /home/vega/vegavisor_home/current/vega unsafe_reset_all --home /home/vega/vega_home
    /home/vega/vegavisor_home/current/vega tm unsafe_reset_all --home /home/vega/tendermint_home
  args:
    executable: /bin/bash

- name: Unsafe reset all for data node
  changed_when: true # always impact the node
  become: true
  become_user: vega
  ansible.builtin.shell: |
    set -o pipefail

    /home/vega/vegavisor_home/current/vega datanode unsafe_reset_all --home /home/vega/vega_home
  args:
    executable: /bin/bash
  when: vega_core_with_data_node

- name: Restart postgresql to kill all connections
  ansible.builtin.service:
    state: restarted
    enabled: true
    name: postgresql
  when: "'postgresql.service' in services"

- name: Wait for postgresql to be ready
  ansible.builtin.wait_for:
    port: "5432"
    timeout: 300 # seconds
  when: "'postgresql.service' in services"

- name: Delete postgresql databases for vega and
  become: true
  become_user: postgres
  when: "'postgresql.service' in services"
  community.postgresql.postgresql_db:
    name: "{{ item }}"
    port: "5432"
    state: absent
  with_items:
    - vega
    - tendermint

- name: Recreate postgresql databases for vega and
  become: true
  become_user: postgres
  when: "'postgresql.service' in services"
  community.postgresql.postgresql_db:
    name: "{{ item }}"
    port: "5432"
    state: present
  with_items:
    - vega
    - tendermint

- name: Update genesis version for visor binary
  ansible.builtin.copy:
    remote_src: true
    src: /usr/local/bin/visor
    dest: /home/vega/vegavisor_home/visor
    owner: vega
    group: vega
    mode: '0755'

- name: Update genesis version for vega binary
  ansible.builtin.copy:
    remote_src: true
    src: /usr/local/bin/vega
    dest: /home/vega/vegavisor_home/current/vega
    owner: vega
    group: vega
    mode: '0755'
