---
- name: Restart vegavisor
  ansible.builtin.service:
    state: "restarted"
    daemon_reload: true

    name: vegavisor
  listen: "Restart vegavisor"
  when: not ansible_check_mode

- name: Restart blockexplorer
  ansible.builtin.service:
    state: "restarted"
    daemon_reload: true
    name: blockexplorer
  listen: "Restart blockexplorer"
  when: not ansible_check_mode
