---
- name: Restart vegavisor
  ansible.builtin.service:
    state: "{{- 'restarted' if vega_core_run_network else 'stopped' -}}"
    daemon_reload: true
    enabled: true
    name: vegavisor
  listen: "Restart vegavisor"
  when: not ansible_check_mode

- name: Restart blockexplorer
  ansible.builtin.service:
    # it may be started anytime and during first startup it initialize the database, 
    # so it should be started as soon as possible ideally before the vegavisor
    state: "started"
    daemon_reload: true
    enabled: true
    name: blockexplorer
  listen: "Restart blockexplorer"
  when: not ansible_check_mode

- name: Restart vega-health-check
  ansible.builtin.service:
    state: "{{- 'restarted' if vega_core_run_network else 'stopped' -}}"
    daemon_reload: true
    enabled: true
    name: vega-health-check
  listen: "Restart vega-health-check"
  when: not ansible_check_mode
