---
- name: Take snapshot of all the servers
  hosts: put_here_the_network_name
  become: true
  become_user: root
  roles:
    - role: vega-zfs-snapshot
      vars:
        vega_zfs_snapshot_rollback: true

# Example: ansible-playbook vega-network-zfs-snapshot.yaml --extra-vars "vega_zfs_snapshot_create_snapshot_name=manual-snapshot1"